version: "3"

networks:
  public: {}

volumes:
  grafana_lib: {}
  prometheus_data: {}
  prometheus_config:
    driver_opts:
      type: tmpfs
      device: tmpfs

services:
  config-concat:
    image: deanwilson/promconf-concat:0.1.0
    volumes:
      - prometheus_config:/fragments/
      - ${PWD}/prometheus-server/config/base_prometheus.yml:/base_prometheus.yml

  prometheus:
    image: prom/prometheus:v2.1.0
    ports:
      - 9090:9090
    network_mode: host
    volumes:
      - prometheus_data:/prometheus
      - prometheus_config:/fragments/
      - ${PWD}/prometheus-server/config/targets/prometheus.json:/etc/prometheus/targets/prometheus.json
      - ${PWD}/prometheus-server/config/targets/grafana.json:/etc/prometheus/targets/grafana.json
      - ${PWD}/prometheus-server/config/targets/dejaq.json:/etc/prometheus/targets/dejaq.json
    command:
      - '--config.file=/fragments/complete/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana:5.1.3
    ports:
      - "3000:3000"
    network_mode: host
    volumes:
      - grafana_lib:/var/lib/grafana
      - ${PWD}/prometheus-server/config/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret

  dejaq:
    image: golang:1.13.1-alpine
    ports:
      - "2112:2112"
    network_mode: host
    volumes:
      - ../../../:/go/src/dejaq
    working_dir: /go/src/dejaq/broker/cmd/base
    command: go run main.go