// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package DejaQ

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AcknowledgeMessages struct {
	_tab flatbuffers.Table
}

func GetRootAsAcknowledgeMessages(buf []byte, offset flatbuffers.UOffsetT) *AcknowledgeMessages {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AcknowledgeMessages{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *AcknowledgeMessages) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AcknowledgeMessages) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AcknowledgeMessages) Id() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AcknowledgeMessages) MutateId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *AcknowledgeMessages) Partition() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AcknowledgeMessages) MutatePartition(n uint16) bool {
	return rcv._tab.MutateUint16Slot(6, n)
}

func AcknowledgeMessagesStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func AcknowledgeMessagesAddId(builder *flatbuffers.Builder, id uint64) {
	builder.PrependUint64Slot(0, id, 0)
}
func AcknowledgeMessagesAddPartition(builder *flatbuffers.Builder, partition uint16) {
	builder.PrependUint16Slot(1, partition, 0)
}
func AcknowledgeMessagesEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
