// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package DejaQ

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ConsumerAcknowledgeRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsConsumerAcknowledgeRequest(buf []byte, offset flatbuffers.UOffsetT) *ConsumerAcknowledgeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ConsumerAcknowledgeRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ConsumerAcknowledgeRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ConsumerAcknowledgeRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ConsumerAcknowledgeRequest) Ids(j int) uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *ConsumerAcknowledgeRequest) IdsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ConsumerAcknowledgeRequest) MutateIds(j int, n uint64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

func ConsumerAcknowledgeRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ConsumerAcknowledgeRequestAddIds(builder *flatbuffers.Builder, ids flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(ids), 0)
}
func ConsumerAcknowledgeRequestStartIdsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func ConsumerAcknowledgeRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
