// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package DejaQ

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ProduceRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsProduceRequest(buf []byte, offset flatbuffers.UOffsetT) *ProduceRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ProduceRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ProduceRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ProduceRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ProduceRequest) Priority() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ProduceRequest) MutatePriority(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *ProduceRequest) Body(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ProduceRequest) BodyLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ProduceRequest) BodyBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ProduceRequest) MutateBody(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func ProduceRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ProduceRequestAddPriority(builder *flatbuffers.Builder, priority uint16) {
	builder.PrependUint16Slot(0, priority, 0)
}
func ProduceRequestAddBody(builder *flatbuffers.Builder, body flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(body), 0)
}
func ProduceRequestStartBodyVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ProduceRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
