// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package DejaQ

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ProduceResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsProduceResponse(buf []byte, offset flatbuffers.UOffsetT) *ProduceResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ProduceResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ProduceResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ProduceResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ProduceResponse) Ack() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ProduceResponse) MutateAck(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func ProduceResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ProduceResponseAddAck(builder *flatbuffers.Builder, ack bool) {
	builder.PrependBoolSlot(0, ack, false)
}
func ProduceResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
