// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package DejaQ

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TimelineConsumerHandshakeResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsTimelineConsumerHandshakeResponse(buf []byte, offset flatbuffers.UOffsetT) *TimelineConsumerHandshakeResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TimelineConsumerHandshakeResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TimelineConsumerHandshakeResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TimelineConsumerHandshakeResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TimelineConsumerHandshakeResponse) SessionID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TimelineConsumerHandshakeResponse) Err(obj *Error) *Error {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Error)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func TimelineConsumerHandshakeResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TimelineConsumerHandshakeResponseAddSessionID(builder *flatbuffers.Builder, sessionID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(sessionID), 0)
}
func TimelineConsumerHandshakeResponseAddErr(builder *flatbuffers.Builder, err flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(err), 0)
}
func TimelineConsumerHandshakeResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
