// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package DejaQ

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TimelineConsumerHandshakeRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsTimelineConsumerHandshakeRequest(buf []byte, offset flatbuffers.UOffsetT) *TimelineConsumerHandshakeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TimelineConsumerHandshakeRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TimelineConsumerHandshakeRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TimelineConsumerHandshakeRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TimelineConsumerHandshakeRequest) TraceID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TimelineConsumerHandshakeRequest) TimeoutMS() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TimelineConsumerHandshakeRequest) MutateTimeoutMS(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *TimelineConsumerHandshakeRequest) ConsumerID(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *TimelineConsumerHandshakeRequest) ConsumerIDLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TimelineConsumerHandshakeRequest) ConsumerIDBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TimelineConsumerHandshakeRequest) MutateConsumerID(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *TimelineConsumerHandshakeRequest) TopicID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TimelineConsumerHandshakeRequest) Cluster() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TimelineConsumerHandshakeRequest) LeaseTimeoutMS() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TimelineConsumerHandshakeRequest) MutateLeaseTimeoutMS(n uint64) bool {
	return rcv._tab.MutateUint64Slot(14, n)
}

func TimelineConsumerHandshakeRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func TimelineConsumerHandshakeRequestAddTraceID(builder *flatbuffers.Builder, traceID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(traceID), 0)
}
func TimelineConsumerHandshakeRequestAddTimeoutMS(builder *flatbuffers.Builder, timeoutMS uint64) {
	builder.PrependUint64Slot(1, timeoutMS, 0)
}
func TimelineConsumerHandshakeRequestAddConsumerID(builder *flatbuffers.Builder, consumerID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(consumerID), 0)
}
func TimelineConsumerHandshakeRequestStartConsumerIDVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func TimelineConsumerHandshakeRequestAddTopicID(builder *flatbuffers.Builder, topicID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(topicID), 0)
}
func TimelineConsumerHandshakeRequestAddCluster(builder *flatbuffers.Builder, cluster flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(cluster), 0)
}
func TimelineConsumerHandshakeRequestAddLeaseTimeoutMS(builder *flatbuffers.Builder, leaseTimeoutMS uint64) {
	builder.PrependUint64Slot(5, leaseTimeoutMS, 0)
}
func TimelineConsumerHandshakeRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
