// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package DejaQ

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TimelineExtendLeaseRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsTimelineExtendLeaseRequest(buf []byte, offset flatbuffers.UOffsetT) *TimelineExtendLeaseRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TimelineExtendLeaseRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TimelineExtendLeaseRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TimelineExtendLeaseRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TimelineExtendLeaseRequest) TraceID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TimelineExtendLeaseRequest) TimeoutMS() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TimelineExtendLeaseRequest) MutateTimeoutMS(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *TimelineExtendLeaseRequest) SessionID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TimelineExtendLeaseRequest) MessageID(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *TimelineExtendLeaseRequest) MessageIDLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TimelineExtendLeaseRequest) MessageIDBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TimelineExtendLeaseRequest) MutateMessageID(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func TimelineExtendLeaseRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func TimelineExtendLeaseRequestAddTraceID(builder *flatbuffers.Builder, traceID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(traceID), 0)
}
func TimelineExtendLeaseRequestAddTimeoutMS(builder *flatbuffers.Builder, timeoutMS uint64) {
	builder.PrependUint64Slot(1, timeoutMS, 0)
}
func TimelineExtendLeaseRequestAddSessionID(builder *flatbuffers.Builder, sessionID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(sessionID), 0)
}
func TimelineExtendLeaseRequestAddMessageID(builder *flatbuffers.Builder, messageID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(messageID), 0)
}
func TimelineExtendLeaseRequestStartMessageIDVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func TimelineExtendLeaseRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
