// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package DejaQ

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TimelinePushLeaseResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsTimelinePushLeaseResponse(buf []byte, offset flatbuffers.UOffsetT) *TimelinePushLeaseResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TimelinePushLeaseResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TimelinePushLeaseResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TimelinePushLeaseResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TimelinePushLeaseResponse) TraceID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TimelinePushLeaseResponse) TimeoutMS() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TimelinePushLeaseResponse) MutateTimeoutMS(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *TimelinePushLeaseResponse) ExpirationTSMSUTC() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TimelinePushLeaseResponse) MutateExpirationTSMSUTC(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *TimelinePushLeaseResponse) ConsumerID(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *TimelinePushLeaseResponse) ConsumerIDLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TimelinePushLeaseResponse) ConsumerIDBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TimelinePushLeaseResponse) MutateConsumerID(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *TimelinePushLeaseResponse) Message(obj *TimelinePushLeaseMessage) *TimelinePushLeaseMessage {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(TimelinePushLeaseMessage)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func TimelinePushLeaseResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func TimelinePushLeaseResponseAddTraceID(builder *flatbuffers.Builder, traceID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(traceID), 0)
}
func TimelinePushLeaseResponseAddTimeoutMS(builder *flatbuffers.Builder, timeoutMS uint64) {
	builder.PrependUint64Slot(1, timeoutMS, 0)
}
func TimelinePushLeaseResponseAddExpirationTSMSUTC(builder *flatbuffers.Builder, expirationTSMSUTC uint64) {
	builder.PrependUint64Slot(2, expirationTSMSUTC, 0)
}
func TimelinePushLeaseResponseAddConsumerID(builder *flatbuffers.Builder, consumerID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(consumerID), 0)
}
func TimelinePushLeaseResponseStartConsumerIDVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func TimelinePushLeaseResponseAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(message), 0)
}
func TimelinePushLeaseResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
