// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package DejaQ

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TimelineCountResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsTimelineCountResponse(buf []byte, offset flatbuffers.UOffsetT) *TimelineCountResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TimelineCountResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TimelineCountResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TimelineCountResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TimelineCountResponse) Result() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TimelineCountResponse) MutateResult(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *TimelineCountResponse) Err(obj *Error) *Error {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Error)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func TimelineCountResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TimelineCountResponseAddResult(builder *flatbuffers.Builder, result uint64) {
	builder.PrependUint64Slot(0, result, 0)
}
func TimelineCountResponseAddErr(builder *flatbuffers.Builder, err flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(err), 0)
}
func TimelineCountResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
