// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package DejaQ

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TimelineDeleteRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsTimelineDeleteRequest(buf []byte, offset flatbuffers.UOffsetT) *TimelineDeleteRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TimelineDeleteRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TimelineDeleteRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TimelineDeleteRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TimelineDeleteRequest) MessageID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TimelineDeleteRequest) Version() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TimelineDeleteRequest) MutateVersion(n uint16) bool {
	return rcv._tab.MutateUint16Slot(6, n)
}

func TimelineDeleteRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TimelineDeleteRequestAddMessageID(builder *flatbuffers.Builder, messageID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(messageID), 0)
}
func TimelineDeleteRequestAddVersion(builder *flatbuffers.Builder, version uint16) {
	builder.PrependUint16Slot(1, version, 0)
}
func TimelineDeleteRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
