// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package DejaQ

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TimelineSubscribeRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsTimelineSubscribeRequest(buf []byte, offset flatbuffers.UOffsetT) *TimelineSubscribeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TimelineSubscribeRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TimelineSubscribeRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TimelineSubscribeRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TimelineSubscribeRequest) TraceID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TimelineSubscribeRequest) TimeoutMS() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TimelineSubscribeRequest) MutateTimeoutMS(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *TimelineSubscribeRequest) ConsumerID(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *TimelineSubscribeRequest) ConsumerIDLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TimelineSubscribeRequest) ConsumerIDBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TimelineSubscribeRequest) MutateConsumerID(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *TimelineSubscribeRequest) TopicID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TimelineSubscribeRequest) Cluster() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TimelineSubscribeRequest) LeaseTimeoutMS() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TimelineSubscribeRequest) MutateLeaseTimeoutMS(n uint64) bool {
	return rcv._tab.MutateUint64Slot(14, n)
}

func TimelineSubscribeRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func TimelineSubscribeRequestAddTraceID(builder *flatbuffers.Builder, traceID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(traceID), 0)
}
func TimelineSubscribeRequestAddTimeoutMS(builder *flatbuffers.Builder, timeoutMS uint64) {
	builder.PrependUint64Slot(1, timeoutMS, 0)
}
func TimelineSubscribeRequestAddConsumerID(builder *flatbuffers.Builder, consumerID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(consumerID), 0)
}
func TimelineSubscribeRequestStartConsumerIDVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func TimelineSubscribeRequestAddTopicID(builder *flatbuffers.Builder, topicID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(topicID), 0)
}
func TimelineSubscribeRequestAddCluster(builder *flatbuffers.Builder, cluster flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(cluster), 0)
}
func TimelineSubscribeRequestAddLeaseTimeoutMS(builder *flatbuffers.Builder, leaseTimeoutMS uint64) {
	builder.PrependUint64Slot(5, leaseTimeoutMS, 0)
}
func TimelineSubscribeRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
