// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package DejaQ

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TimelineCountRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsTimelineCountRequest(buf []byte, offset flatbuffers.UOffsetT) *TimelineCountRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TimelineCountRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TimelineCountRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TimelineCountRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TimelineCountRequest) TraceID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TimelineCountRequest) TimeoutMS() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TimelineCountRequest) MutateTimeoutMS(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *TimelineCountRequest) Status() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TimelineCountRequest) MutateStatus(n byte) bool {
	return rcv._tab.MutateByteSlot(8, n)
}

func (rcv *TimelineCountRequest) TimeStart() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TimelineCountRequest) MutateTimeStart(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *TimelineCountRequest) TimeEnd() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TimelineCountRequest) MutateTimeEnd(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func TimelineCountRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func TimelineCountRequestAddTraceID(builder *flatbuffers.Builder, traceID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(traceID), 0)
}
func TimelineCountRequestAddTimeoutMS(builder *flatbuffers.Builder, timeoutMS uint64) {
	builder.PrependUint64Slot(1, timeoutMS, 0)
}
func TimelineCountRequestAddStatus(builder *flatbuffers.Builder, status byte) {
	builder.PrependByteSlot(2, status, 0)
}
func TimelineCountRequestAddTimeStart(builder *flatbuffers.Builder, timeStart uint64) {
	builder.PrependUint64Slot(3, timeStart, 0)
}
func TimelineCountRequestAddTimeEnd(builder *flatbuffers.Builder, timeEnd uint64) {
	builder.PrependUint64Slot(4, timeEnd, 0)
}
func TimelineCountRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
