// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package DejaQ

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TimelineReleaseRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsTimelineReleaseRequest(buf []byte, offset flatbuffers.UOffsetT) *TimelineReleaseRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TimelineReleaseRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TimelineReleaseRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TimelineReleaseRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TimelineReleaseRequest) TraceID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TimelineReleaseRequest) TimeoutMS() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TimelineReleaseRequest) MutateTimeoutMS(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *TimelineReleaseRequest) SessionID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TimelineReleaseRequest) MessageID(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *TimelineReleaseRequest) MessageIDLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TimelineReleaseRequest) MessageIDBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TimelineReleaseRequest) MutateMessageID(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *TimelineReleaseRequest) TimestampMS() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TimelineReleaseRequest) MutateTimestampMS(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func (rcv *TimelineReleaseRequest) Version() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TimelineReleaseRequest) MutateVersion(n uint16) bool {
	return rcv._tab.MutateUint16Slot(14, n)
}

func TimelineReleaseRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func TimelineReleaseRequestAddTraceID(builder *flatbuffers.Builder, traceID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(traceID), 0)
}
func TimelineReleaseRequestAddTimeoutMS(builder *flatbuffers.Builder, timeoutMS uint64) {
	builder.PrependUint64Slot(1, timeoutMS, 0)
}
func TimelineReleaseRequestAddSessionID(builder *flatbuffers.Builder, sessionID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(sessionID), 0)
}
func TimelineReleaseRequestAddMessageID(builder *flatbuffers.Builder, messageID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(messageID), 0)
}
func TimelineReleaseRequestStartMessageIDVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func TimelineReleaseRequestAddTimestampMS(builder *flatbuffers.Builder, timestampMS uint64) {
	builder.PrependUint64Slot(4, timestampMS, 0)
}
func TimelineReleaseRequestAddVersion(builder *flatbuffers.Builder, version uint16) {
	builder.PrependUint16Slot(5, version, 0)
}
func TimelineReleaseRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
