// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package DejaQ

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TimelineConsumeRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsTimelineConsumeRequest(buf []byte, offset flatbuffers.UOffsetT) *TimelineConsumeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TimelineConsumeRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TimelineConsumeRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TimelineConsumeRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TimelineConsumeRequest) TraceID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TimelineConsumeRequest) TimeoutMS() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TimelineConsumeRequest) MutateTimeoutMS(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *TimelineConsumeRequest) SessionID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func TimelineConsumeRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func TimelineConsumeRequestAddTraceID(builder *flatbuffers.Builder, traceID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(traceID), 0)
}
func TimelineConsumeRequestAddTimeoutMS(builder *flatbuffers.Builder, timeoutMS uint64) {
	builder.PrependUint64Slot(1, timeoutMS, 0)
}
func TimelineConsumeRequestAddSessionID(builder *flatbuffers.Builder, sessionID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(sessionID), 0)
}
func TimelineConsumeRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
