// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package DejaQ

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TimelinePushLeaseSubscribeRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsTimelinePushLeaseSubscribeRequest(buf []byte, offset flatbuffers.UOffsetT) *TimelinePushLeaseSubscribeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TimelinePushLeaseSubscribeRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TimelinePushLeaseSubscribeRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TimelinePushLeaseSubscribeRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TimelinePushLeaseSubscribeRequest) TraceID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TimelinePushLeaseSubscribeRequest) TimeoutMS() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TimelinePushLeaseSubscribeRequest) MutateTimeoutMS(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *TimelinePushLeaseSubscribeRequest) ConsumerID(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *TimelinePushLeaseSubscribeRequest) ConsumerIDLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TimelinePushLeaseSubscribeRequest) ConsumerIDBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TimelinePushLeaseSubscribeRequest) MutateConsumerID(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func TimelinePushLeaseSubscribeRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func TimelinePushLeaseSubscribeRequestAddTraceID(builder *flatbuffers.Builder, traceID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(traceID), 0)
}
func TimelinePushLeaseSubscribeRequestAddTimeoutMS(builder *flatbuffers.Builder, timeoutMS uint64) {
	builder.PrependUint64Slot(1, timeoutMS, 0)
}
func TimelinePushLeaseSubscribeRequestAddConsumerID(builder *flatbuffers.Builder, consumerID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(consumerID), 0)
}
func TimelinePushLeaseSubscribeRequestStartConsumerIDVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func TimelinePushLeaseSubscribeRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
