// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package DejaQ

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TimelineCountRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsTimelineCountRequest(buf []byte, offset flatbuffers.UOffsetT) *TimelineCountRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TimelineCountRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TimelineCountRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TimelineCountRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TimelineCountRequest) Status() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TimelineCountRequest) MutateStatus(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *TimelineCountRequest) TimeStart() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TimelineCountRequest) MutateTimeStart(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *TimelineCountRequest) TimeEnd() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TimelineCountRequest) MutateTimeEnd(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func TimelineCountRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func TimelineCountRequestAddStatus(builder *flatbuffers.Builder, status byte) {
	builder.PrependByteSlot(0, status, 0)
}
func TimelineCountRequestAddTimeStart(builder *flatbuffers.Builder, timeStart uint64) {
	builder.PrependUint64Slot(1, timeStart, 0)
}
func TimelineCountRequestAddTimeEnd(builder *flatbuffers.Builder, timeEnd uint64) {
	builder.PrependUint64Slot(2, timeEnd, 0)
}
func TimelineCountRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
