// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package server

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ErrorDetails struct {
	_tab flatbuffers.Table
}

func GetRootAsErrorDetails(buf []byte, offset flatbuffers.UOffsetT) *ErrorDetails {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ErrorDetails{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ErrorDetails) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ErrorDetails) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ErrorDetails) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ErrorDetails) Value() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ErrorDetailsStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ErrorDetailsAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func ErrorDetailsAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(value), 0)
}
func ErrorDetailsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
