# on top of docker-compose.yml adds 2 more consumers and increases the producer rate to 15k msgs/s
version: "3"

services:
  producer1:
    environment:
      CONSTANT_TICK_DURATION: 1s
      CONSTANT_TICK_COUNT: 15000
      BATCH_SIZE: 5000

  consumer1:
    environment:
      MAX_BUFFER_SIZE: 5000

  consumer2:
    image: dejaq/testsyncconsumer:latest
    depends_on:
      - broker
      - producer1
    environment:
      OVERSEER: 'broker:9000'
      TOPIC: 'compose1'
      TIMEOUT: ''
      CONSUMER_ID: 'c1-consumer2'
      MAX_BUFFER_SIZE: 5000

  consumer3:
    image: dejaq/testsyncconsumer:latest
    depends_on:
      - broker
      - producer1
    environment:
      OVERSEER: 'broker:9000'
      TOPIC: 'compose1'
      TIMEOUT: ''
      CONSUMER_ID: 'c1-consumer3'
      MAX_BUFFER_SIZE: 5000
