version: "3"

services:
  prometheus:
    image: prom/prometheus:v2.17.2
    ports:
      - 9090:9090
    volumes:
      - ${PWD}/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PWD}/config/targets/prometheus.json:/etc/prometheus/targets/prometheus.json
      - ${PWD}/config/targets/base.json:/etc/prometheus/targets/base.json
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'