// Code generated by "stringer -type=Module,Severity"; DO NOT EDIT.

package errors

import "strconv"

const _Module_name = "InternalClusterStorageBrokerProtocolDriver"

var _Module_index = [...]uint8{0, 8, 15, 22, 28, 36, 42}

func (i Module) String() string {
	if i >= Module(len(_Module_index)-1) {
		return "Module(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Module_name[_Module_index[i]:_Module_index[i+1]]
}

const _Severity_name = "FatalPanicErrorWarningNoticeDebug"

var _Severity_index = [...]uint8{0, 5, 10, 15, 22, 28, 33}

func (i Severity) String() string {
	i -= 7
	if i >= Severity(len(_Severity_index)-1) {
		return "Severity(" + strconv.FormatInt(int64(i+7), 10) + ")"
	}
	return _Severity_name[_Severity_index[i]:_Severity_index[i+1]]
}
