name: Push test sync producer docker

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: docker build . --file ./broker/producer.dockerfile --tag dejaq/testsyncproducer:latest
    - name: Push the image
      run: docker push dejaq/testsyncproducer:latest
