name: Push test Dejaq-complete docker

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the Producer Docker image
      run: docker build . --file producer.dockerfile --tag dejaq/testsyncproducer:latest
    - name: Push the Producer image
      run: docker push dejaq/testsyncproducer:latest
    - name: Build the Consumer Docker image
      run: docker build . --file consumer.dockerfile --tag dejaq/testsyncconsumer:latest
    - name: Push the Consumer image
      run: docker push dejaq/testsyncconsumer:latest
    - name: Build the Broker Docker image
      run: docker build . --file broker.dockerfile --tag dejaq/testsyncbroker:latest
    - name: Push the Broker image
      run: docker push dejaq/testsyncbroker:latest
